### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by CodaFi**
- Increase our build target
- Box is dead (should we replace it with Id<T>?)
- Removes dead sections

### CODE REVIEW

**Comment by CodaFi** [comment]
Oh boy, Travis is going to love eating this.

**Comment by griotspeak** [comment]
Box|id is not completely useless yet since [“Indirect cases” still need boxing](https://twitter.com/jckarter/status/608030741214068736).

**Comment by CodaFi** [comment]
I am holding out hope it will be useless by the time GM rolls around.  If that doesn't pan out then I'll revert the last one there.

**Comment by CodaFi** [comment]
This will be merged into a new `swift-development` branch.  Closing this version.

**Pull request closed without merging**
