### PR TITLE
[WIP] Swift 1.2

### PR DESCRIPTION
**Pull request by CodaFi**
:warning: Not to be merged until Xcode 6.3 goes public :warning:

### CODE REVIEW

**Comment by pthariensflame** [comment]
Some of the copyrights still need to be changed.

**Comment by CodaFi** [comment]
I'll have to talk to Max about a few of the files in here.  Everything I could change, I have.

**Comment by CodaFi** [comment]
OK, all that's left is the travis-ci/travis-ci#3216 block.

**Comment by CodaFi** [comment]
Merging this.

:boat:

**Pull request merged**
