### PR TITLE
Add left and right optional properties to Either.

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by CodaFi** [comment]
This is good to merge, but before I do is there another name you'd like to give to these partial projection functions?  Even Haskell doesn't have _great_ names for these things.

**Comment by mpurland** [comment]
I like the name since `left` and `right` is short to reference, what do you think?

**Comment by mpurland** [comment]
Scala's [Either](http://www.scala-lang.org/api/2.11.5/index.html#scala.util.Either) type has `left` but it returns a [LeftProjection](http://www.scala-lang.org/api/2.11.5/index.html#scala.util.Either$$LeftProjection). Perhaps we could do the same but have a LeftProjection that is a Generator to use in a "for in".

**Comment by CodaFi** [comment]
Scala's For-comprehensions are miles ahead of anything I think swift has to offer.  If you're cool with this, I am too.

:boat:

**Pull request merged**
