### PR TITLE
Update for Xcode 8 GM

### PR DESCRIPTION
**Pull request by CosynPa**
@escaping can only be applied to parameters.

### CODE REVIEW

**Comment by CodaFi** [comment]
Thanks!  I'm going to update SwiftCheck myself and let you know when you should `carthage update`.

**Comment by CodaFi** [comment]
Alright, please run `carthage update --use-submodules` and commit the result.

**Comment by CosynPa** [comment]
Updated

**Comment by CodaFi** [comment]
:boat:

**Pull request merged**
